### ISSUE TITLE
Tab crashes after loading

### ISSUE THREAD

**Issue by yuriy636** [boyanio/wasm-wheel#13]
It takes about 5 seconds after loading the page for the tab to crash.

Could reproduce on:
- Desktop Chrome 78.0.3904.108 x64 - Windows 10 1903
- Mobile Chrome 78.0.3904.108 - Android 10 (I had to scroll down to the wheel in order to get the tab to crash)

Couldn't reproduce on:
- Desktop Firefox 71.0 x64 - Windows 10 1903

**Comment by boyanio** [comment]
Thanks for reporting this. I have experienced this issue before too. It seems to be the PHP wheel part that causes it, however I haven't found a solution yet. Maybe one could try to update to the latest build of PHP 7.4
