### ISSUE TITLE
TypeScript != AssemblyScript

### ISSUE THREAD

**Issue by jayphelps** [boyanio/wasm-wheel#2]
Very fun demo! Any objections to changing "TypeScript" to "AssemblyScript"? I discuss and introduce wasm a lot with people in the community and constantly battle the perception that people can or will compile JavaScript/TypeScript/Flow to wasm when that is not the case. AssemblyScript is close to a subset, but technically not one. If they do make it 100% a subset the distinction is still rather huge in practice IMO. I want to link this demo to people but don't want people confused! 😄 

> Every AssemblyScript program is valid TypeScript syntactically, but not necessarily semantically.

https://github.com/AssemblyScript/assemblyscript#how-it-works

**Comment by boyanio** [comment]
Hey @jayphelps. Thanks for starting this topic. I see your point. Most places I've seen, people refer to it as TypeScript compilation to WebAssembly, but as AssemblyScript is a (nearly 100%) subset of TypeScript, I would agree with you that it is not interchangeable. I will rename it soon to avoid further confusion. (y)

**Comment by dcodeIO** [comment]
But, portable AssemblyScript, a subset of a variant of a superset of JavaScript that also compiles to JavaScript using tsc, has been specifically created for <del>confusion</del> battling perceptions.

**Comment by jayphelps** [comment]
@dcodeIO can you elaborate? Do you disagree that calling it TypeScript is confusing?

**Comment by dcodeIO** [comment]
Depends at which exact point in space time a banana isn't a banana anymore. Is it still a banana even when space is bent in a way shifting its reflection's wave length towards a perceived green tone and its form towards that of an apple? Some people's perception might even trick them in believing it doesn't taste like banana now. Maybe we should ask who is at fault. The one who bent the universe and named it a subset of TypeScript or the user concluding that it still tastes like banana? I think we can agree on `tsc` != `asc`, but I am not that sure anymore that AssemblyScript, as a language, does actually exist. Does that imply it is TypeScript?

**Comment by jayphelps** [comment]
Lol I have no idea but the distinction is important 🙂

**Comment by boyanio** [comment]
I think the confusion arises when people start thinking they can compile JavaScript to WebAssembly. When I do workshops and talks about it, I always get such questions and assumptions. Furthermore, many people associate TypeScript with JavaScript, whereas AssemblyScript uses the syntax of TypeScript (which, hey, is ES6+ and some types), but doesn't claim to compile JavaScript to wasm.
